### ISSUE TITLE
Make resolution of Bakery more robust.

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/omnisharp-roslyn#1]
Right now it assumes that version number isn't included in Bakery.

https://github.com/cake-build/omnisharp-roslyn/blob/feature/cake/src/OmniSharp.Cake/Tools/CakeGenerationToolResolver.cs

We should add a more robust strategy for locating Bakery.

**Comment by mholo65** [comment]
@patriksvensson is this good enough? https://github.com/cake-build/omnisharp-roslyn/commit/f4e6d91d74a4eca90896005420e267243b497d8e

**Comment by patriksvensson** [comment]
@mholo65 It looks good enough. Better than before for sure! 👍

**Comment by mholo65** [comment]
Thanks, closing this then!
